apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rh-trex
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/ysubrama-tenant/rh-trex/rh-trex@sha256:7535ff3a910ef5cb00c8c7c6ba0e9bdd67081f17fc707541d10c9b52288d29e1
        name: trex
        resources: {}
status: {}
